version: "3"
services:
    mongo:
        image: mongo:4.0 
        restart: always
        container_name: "mongo"
        environment:
#            - MONGO_INITDB_ROOT_USERNAME=user
#            - MONGO_INITDB_ROOT_PASSWORD=password
            - MONGO_DATA_DIR=/data/db
            - MONGO_LOG_DIR=/var/log/mongodb
        volumes:
            - data_db:/data/db
            - data_configdb:/data/configdb
        expose: 
            - 27017
        networks:
            - genieacs_network

    genieacs:
        depends_on:
            - 'mongo'
        image: duychu/genieacs:1.1
        container_name: "genieacs"
        ports:
            - "7547:7547"
            - "7557:7557"
            - "7567:7567"
            - "3000:3000"
        volumes:
            - opt_volume:/opt
            - usr_local_share_volume:/usr/local/share
        networks:
            - genieacs_network

    genieacs-sim:
        depends_on:
            - 'genieacs'
        image: drumsergio/genieacs-sim
        container_name: "genieacs-sim"
        networks:
            - genieacs_network
        
volumes:
    data_db:
    data_configdb:
    opt_volume:
    usr_local_share_volume:

networks:
    genieacs_network:
